### ISSUE TITLE
arangodb vs. arangodb

### ISSUE THREAD

**Issue by Thijxx** [arangodb-helper/arangodb#106]
So is this a fork of arangodb or a specialized version of arangodb or a helper? It has the same name as arangodb, namely `arangodb` so I am confused...

**Comment by ewoutp** [comment]
This repository contains the ArangoDB starter utility.
The starter utility is not the database itself, but a utility that will help you get an ArangoDB cluster, single instance server up and running quickly.

It is written independent from the actual database repository but (to add to the confusion), every release of the ArangoDB database now contains a copy of this starter utility (of the binary release).

**Comment by Thijxx** [comment]
thanks :)
