### ISSUE TITLE
Open File Limit exceeded for the Starter

### ISSUE THREAD

**Issue by dashdeep13** [arangodb-helper/arangodb#108]
I am using arangodb starter version 0.10.2 and arangodb version 3.2.3 on CentOS 7. I have setup a cluster with 8 nodes where the first three nodes had - Agent,Coordinator and Dbserver and the other 5 nodes had - Coordinator and Dbserver. I see the that Max File Descriptor Limit for the actual Arangodb process is 8192, however for the starter process itself is 1024. As a result I often see the helper process not able to create new processes(perform any action) and all we see is the error:

Too many open files for Accept (TCP) Error

I am not exactly sure how to reproduce the error, but going to file descriptor for the process I saw that the limit of 1024 was reached.
Can we increase the limit to 8192 for even the starter?

**Comment by ewoutp** [comment]
Increasing the limit would be a possibility, but I believe the limit should have to be raised.
I suspect there is a leak somewhere. We'll investigate and get back as soon as we know more.

**Comment by ewoutp** [comment]
@dashdeep13 Can you describe exactly how you use the starter?
(on what OS, docker or normal processes, which arguments and so on)

**Comment by ewoutp** [comment]
We've made a change in the starter that should fix this problem.
I'll leave the issue open until we do a next release. (starter will be released today, arangod including starter soon)

**Comment by sleto-it** [comment]
Thanks @ewoutp . The OS is Red Hat

So as far as I understand @dashdeep13 can keep using ArangoDB 3.2.9, but he has to download the new starter (v. 0.10.4) from [here](https://github.com/arangodb-helper/arangodb/releases/tag/0.10.4) and use the `arangodb` binary coming from this 0.10.4 release, instead of the one included in the official 3.2.9 package

Then as soon as 3.2.10 will be released, this new version of the starter will be included by default (or a newer one - in case it has been released in the meantime)

Is my understanding correct?

Many thanks,

**Comment by ewoutp** [comment]
@sleto-it That is correct

**Comment by dashdeep13** [comment]
Thanks @ewoutp and @sleto-it for looking into this. A quick question:
"starter will be released today, arangod including starter soon"

Currently I maintain different tasks in my ansible to use the arangodb-starter and the arangodb binary itself. Does the arangod already contain the starter? or vice-versa? How can we use the starter out of the arangod binary(if it is present as a sub package).

**Comment by sleto-it** [comment]
Hi @dashdeep13 - you are welcome

The *starter* is the binary *arangodb*. It is included in the official distribution of ArangoDB, so in general, no need to have different tasks in ansible. Just use the official distribution of ArangoDB and it will include the starter as well (in addition to the binary package *arangod*, that is included as well)

In some cases, like the one we had with this ticket, when we fix an issue in the *starter* soon after the release of an official ArangoDB distribution, it may make sense to download the starter directly, and replace it in your distribution. But again, typically this is not needed

When you start a single server (standalone) you can use the binary *arangod*. When you want to start a cluster, you can use the *starter* (binary *arangodb*) - both are in the official distribution

Hope this helps,

**Comment by dashdeep13** [comment]
Thank you, that definitely helps :)

**Comment by sonali-mishra-22** [comment]
Fixed in #109
