### ISSUE TITLE
Resilient SingleServer Mode - Improve Starter Logs

### ISSUE THREAD

**Issue by mchacki** [arangodb-helper/arangodb#110]
In the resilient single server mode all starters print:

    2017/12/13 10:38:53 Your resilient single server can now be accessed with a browser at `https://myAddress:1338` or
    2017/12/13 10:38:53 using `arangosh --server.endpoint ssl://myAddress:1338`.

However only the "leader" will actually respond.
It would be nicer if all three starters print the address of the leader instead.

**Comment by sleto-it** [comment]
or not reporting anything, but on the leader .    

right now the follower produces a message that is confusing, because it gives you an endpoint where you cannot do anything

agree this has to be fixed / improved

**Comment by ewoutp** [comment]
In PR #143 I've changed it such that only the starter the runs the leader will print this message.
