### ISSUE TITLE
Exit with nonzero error code if cluster could not be started

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/arangodb#111]
Currently, if for example an agent could not be started for 100 times, then the starter exits (which is probably OK), but it exits with error code 0. A systemd script with `Restart: on-failure` will then no longer restart the starter, which is probably not what we want.

**Comment by patrickboland4** [comment]
@neunhoef What might cause the agent to fail 100 times? Presently I am encountering this issue, despite following the instructions in the arangodb tutorial

**Comment by ewoutp** [comment]
@patrickboland4 there are numerous situation that can cause a 100 (or a lot more) quick failure.
To figure out which is the case, first look in the log file of the server that does not start. For agents that can be found in `<data-dir>/agent<port>/arangod.log`

**Comment by jsteemann** [comment]
Just verified that when passing a wrong option to the starter, it prints an "unknown flag" error and exits with exit code 0. IMO it should at least return a non-zero exit code here.
