### ISSUE TITLE
setup.json shows wrong Port for starter

### ISSUE THREAD

**Issue by sebastienpattyn93** [arangodb-helper/arangodb#113]
This can probably be seen as an addition to issue #76.  This my `setup.json` file on the node with Ip-address: `10.128.0.4`. The Node has been removed first when it Used DataDir: `opt/arangodb/arangodb_2` . Now a node has been added(clean machine) and received the same IP but I gave another Data-dir: `opt/arangodb/arangodb_4` .

`{"version":"0.2.2","id":"8c98a505","peers":{"Peers":[{"ID":"14f3ca5a","Address":"10.128.0.2","Port":8528,"PortOffset":0,"DataDir":"/opt/arangodb/arangodb_0","HasAgent":true,"IsSecure":false},{"ID":"4058889e","Address":"10.128.0.3","Port":8528,"PortOffset":0,"DataDir":"/opt/arangodb/arangodb_1","HasAgent":true,"HasResilientSingle":true,"IsSecure":false},{"ID":"afa35481","Address":"10.128.0.4","Port":8528,"PortOffset":0,"DataDir":"/opt/arangodb/arangodb_2","HasAgent":true,"HasResilientSingle":true,"IsSecure":false},{"ID":"2045d0b1","Address":"10.128.0.5","Port":8528,"PortOffset":0,"DataDir":"/opt/arangodb/arangodb_3","HasAgent":false,"HasResilientSingle":true,"IsSecure":false},{"ID":"8c98a505","Address":"10.128.0.4","Port":8528,"PortOffset":5,"DataDir":"/opt/arangodb/arangodb_4","HasAgent":false,"HasResilientSingle":true,"IsSecure":false}],"AgencySize":3,"LastModified":"2017-12-20T15:51:03.501801032Z"},"mode":"cluster"}`

I noticed that my port for DataDir: `opt/arangodb/arangodb_4` Is still 8528. When I try to execute a GET request:

```
# curl -X GET http://127.0.0.1:8528/process
curl: (7) Failed to connect to 127.0.0.1 port 8528: Connection refused
```

So the starter is not running on port 8528 anymore. I started looking and since I noticed that my new coordinator was running on port 8534 I tried the following API-call on port 8533:

```
 curl -X GET http://127.0.0.1:8533/process
{"servers-started":true,"servers":[{"type":"coordinator","ip":"10.128.0.4","port":8534,"pid":16392},{"type":"dbserver","ip":"10.128.0.4","port":8535,"pid":16322}]}
```

There I saw that my starter was running there. I need to know where my new starter is running because there might be a situation where there are no starters in my cluster running on port 8528. Then I have to know what other port I have to use to connect a new Node. Any other way how I can see where my starter is running?

**Comment by ewoutp** [comment]
The starter is listening on `Port` + `PortOffset`. This is done to support scenario's where multiple starters are started on the same IP address. Since the remaining starters are still under the impression that a starter should exist on `10.128.0.4` a portoffset of 5 is used, resulting in 8533.
