### ISSUE TITLE
3.2.9  upgrade to 3.3.0 ,agent has terminated, quickly

### ISSUE THREAD

**Issue by Mokwing** [arangodb-helper/arangodb#114]

**Comment by moxiaoyu100** [comment]
There are two problems, 
one is 3.2.9 upgrade to 3.3.0 ,“agent has terminated, quickly” always 
![image](https://user-images.githubusercontent.com/34149942/34430977-7c0ee104-eca5-11e7-9de6-5c25b95ddb7b.png).
the second is arangosh ,
![image](https://user-images.githubusercontent.com/34149942/34430990-9d582258-eca5-11e7-81be-f93d73b3e4f1.png)

**Comment by sonali-mishra-22** [comment]
Closing issue as 3.2.9 and 3.3.0 have reached end of life.
