### ISSUE TITLE
How to enable authentication?

### ISSUE THREAD

**Issue by dsonet** [arangodb-helper/arangodb#146]
Even I use `arangodb --auth.jwt-secret ./arangodb.jwt` on every node, when I login, visit the 8529 port, still no need username & password? I now have `coordinator8529`, `dbserver8530`, `agent8531` on each db server, how to configure them to enable authentication?

**Comment by ewoutp** [comment]
Did you send the `--auth.jwt-secret` option when you started the `arangodb` for the first time?
This option is persisted in the config files for the coordinator/dbserver/agent instances.

To add it later, you have to edit these config files.
```
[authentication]
jwt-secret = <your jwt file>
```

These config files can be found in the coordinator8529, dbserver8530 & agent8531 sub-directories of the arangodb data dir.

**Comment by dsonet** [comment]
Oh not at the first time...

**Comment by dsonet** [comment]
@ewoutp Oh my, I tried to delete all files and start from bottom to use the --auth.jwt-secret option, after the node joins, it's just crashed by says "Log file for dbserver is empty", Log File for agent is empty....
Tried several times and it just doesn't work. I even reinstall the arangodb...
But, after I tried use no options, it works.....
So is there a fast way that I can enable authentication.

**Comment by ewoutp** [comment]
Please add the exact command lines used and the logs of the starters.

**Comment by dsonet** [comment]
Hi, @ewoutp ,thanks for your attention.
I just followed the guide, on node A, arangodb --auth.jwt-secret ./jwtsecret
On node B,C run arangodb --auth.jwt-secret ./jwtsecret --starter.join A.

Now I already figure it out seems because my jwt secret too long?(48 length). I reduce to 32. But after all it produce another error message, after long logs turn to "Failed to get master URL, retrying in 5sec (Status 401)"

**Comment by dsonet** [comment]
Oh oh oh, finally, figure out how to do make it work.
First start all 3 nodes without auth. stop the them all.
Then edit each node arangod.conf in coordinator8529(and only):
add the following:
jwt-secret = secretstring
authentication = true

Then restart them all. Done, works as I expected.

**Comment by dsonet** [comment]
See here. https://github.com/arangodb-helper/arangodb/issues/10
