### ISSUE TITLE
How to set auto start on ubuntu server?

### ISSUE THREAD

**Issue by dsonet** [arangodb-helper/arangodb#157]
For now it's only auto start the arangod3 service when system restarts, but which not what I want since I use arangodb command setup a cluster already.

**Comment by dsonet** [comment]
For now it's only auto start the arangod3 service, which not what I want since I use arangodb command setup a cluster already

**Comment by ewoutp** [comment]
There is an example in this repo now on how to create a systemd script.
See https://github.com/arangodb-helper/arangodb/tree/master/examples/systemd

Note: The standard ubuntu installer installs a single instance of the database automatically (without using the starter). Make sure to disable that to avoid a port conflict on port 8529.
