### ISSUE TITLE
Virtual terminal processing not enabled?

### ISSUE THREAD

**Issue by Simran-B** [arangodb-helper/arangodb#161]
I ran the following command under latest Windows 10 and you can see that there are ANSI color escape sequences in there:

```
C:\Demo>ArangoDB\usr\bin\arangodb --server.storage-engine rocksdb --starter.data-dir DataArango4 --log.dir Log4 --starter.join 127.0.0.1 --server.arangod=usr\bin\arangod
2018/06/19 19:11:55 Starting arangodb version 0.11.3, build 5c2faa9
2018/06/19 19:11:55 Cannot find [33marangod[0m (expected at [33musr\bin\arangod[0m).
```

In newer Windows 10 version it is required to enable virtual terminal processing to enable colors.

https://github.com/arangodb/arangodb/pull/3753/files#diff-f8eb82ea22f4ab1c37f634cccd6faf1e

**Comment by ewoutp** [comment]
We should consider just disabling coloring on windows.

**Comment by Simran-B** [comment]
I'm fine with either solution.

**Comment by ewoutp** [comment]
PR #164 changed the entire logging behavior, including colors.
Color is now on by default when:
- A terminal is attached to stdin
- AND the process is not running on windows.

The flag can be overwritten by `--log.color=true|false`
