### ISSUE TITLE
Will arangodb-starter support arangodb v3.4?

### ISSUE THREAD

**Issue by CoericK** [arangodb-helper/arangodb#211]
As just was released v3.4, can we continue using arangodb-starter?  Do we need to wait for an upgrade?

**Comment by sleto-it** [comment]
Hi @CoericK ,

Thanks for your question

How did you install ArangoDB?
If you install 3.4.0 it will include a Starter version which is compatible with 3.4.0

The ArangoDB Starter is included in the ArangoDB package. Just use the Starter included in the package

This link might be useful if you plan an upgrade from 3.3.x: https://docs.arangodb.com/3.4/Manual/Upgrading/Starter/

Let us know if this helps,

Thanks,

**Comment by dothebart** [comment]
Closing as answered.
