### ISSUE TITLE
Ouptut hint to arangod options if options don't match

### ISSUE THREAD

**Issue by dothebart** [arangodb-helper/arangodb#222]
as i.e. https://github.com/arangodb/arangodb/issues/8665 showed, the arangodb starter doesn't help users to find out that they should pass options to arangod via a special parameter. 

If a parameter unknown to `arangodb` is specified, please give an explicit hint how to pass `arangod` options.

**Comment by Simran-B** [comment]
Something along "Unknown parameter ... Did you mean to pass through an arangod server option?" would be helpful, yes.

**Comment by jsteemann** [comment]
:+1: for this, as it can be confusing to end users that there are different options for arangodb and options for arangod.
Making the starter hint about how to set options for arangod would be a great help here.
