### ISSUE TITLE
handling of realtive paths

### ISSUE THREAD

**Issue by ObiWahn** [arangodb-helper/arangodb#227]
Hi, I have tried to start `arangod` like this:
```
./arangodb-linux-amd64 --server.arangod ../build/bin/arangod --starter.local
```
But it looks like the starter is not able to find the executable. This is only a guess as the starter does not provide a reason for the fails. The fact that there are no logfiles for the instances and `./arangod_command.txt`  resykts ub `../build/bin/arangod: No such file or directory` support this assumption.

I use the following directory layout:
```
~/arangodb1/                                               -- source dir
~/arangodb1/build         -> ~/arangodb1-build/current     -- symlink
~/arangodb1-build/current -> ~/arangodb1-build/Release     -- symlink
~/arangodb1-build/Release                                  -- real build dir
```

It would really be helpful if the stater could pass reasons for failues like: non existing binaries, wrong rr path, invalid javascript directory, anything that makes arangod fail to the user.

**Comment by jsteemann** [comment]
@ObiWahn : When I try this command (and don't have the arangodb located at that place), my local starter will say something like:
```
2019-07-03T12:09:22+02:00 |ERRO| Cannot find arangod (expected at ../build/bin/arangod). component=arangodb

How to solve this:
1 - Install ArangoDB locally or run the ArangoDB starter in docker. (see README for details).
```
which looks very informative and just right.
Can you recheck if it is just symlink-related, or if the problem has been fixed by now?

**Comment by ObiWahn** [comment]
Yes this error has been fixed indeed.
