### ISSUE TITLE
Improve warning "Flag --all.xxx has been deprecated, Deprecated"

### ISSUE THREAD

**Issue by jsteemann** [arangodb-helper/arangodb#338]
I used a recent version of the starter (from 3.10.0 packages) to start a single server with the following command:
```
arangodb --starter.mode single --starter.data-dir myDir  --all.temp.intermediate-results-path "temp" --all.use-splice-syscall false  
```
Starting the arangod server instance worked, but the first 2 lines of output were:
```
Flag --all.temp.intermediate-results-path has been deprecated, Deprecated
Flag --all.use-splice-syscall has been deprecated, Deprecated
```
These message comes from `./vendor/github.com/spf13/pflag/flag.go`.

Unfortunately the messages are not very helpful for end users. Can they be improved somehow? 
I guess the intention is to tell the end user to not use `--all.*`, but something else. But it is unclear what exactly.

**Comment by nikita-vanyasin** [comment]
^ will be fixed in next release
