### ISSUE TITLE
Fallback to docker image when local `arangod` cannot be found

### ISSUE THREAD

**Issue by ewoutp** [arangodb-helper/arangodb#36]
By default the starter runs `arangod` as (a series of) local processes.
If it cannot find the `arangod` executable it should try to start the servers in a docker container.

This way the time from nothing to a running cluster becomes shorter.

**Comment by ewoutp** [comment]
Given that `arangod` does not play well with file system mapping on mac/windows (map into docker containers), a direct mapping from local process to docker container is not really possible.

Alternatives:
- Start a docker container instead on a newly created docker volume 
- Suggest to start a docker container instead (show how)
- Suggest to install arangod locally
- Both of the 2 suggestions.

**Comment by ewoutp** [comment]
@neunhoef please comment

**Comment by neunhoef** [comment]
I do not like too much automagic. So I am not in favour of silently starting a docker container with a new volume. I like the suggestion idea, though. How about printing "Blablabla not found, please install ArangoDB locally or do blablabla docker."
