### ISSUE TITLE
documentation of alert rules

### ISSUE THREAD

**Issue by neha-kapila94** [arangodb-helper/arangodb#360]
It would be nice to have some example rules we could use to create alerts. Check out https://awesome-prometheus-alerts.grep.to/rules.html for some examples of rules from other exporter tools.

**Comment by nikita-vanyasin** [comment]
Hello @neha-kapila94 
Please checkout next resources that already has some examples on alerting setup:
- https://www.arangodb.com/tutorials/monitoring-collectd-prometheus-grafana/
- https://www.arangodb.com/2020/03/monitoring-arangodb-prometheus-grafana/
- Monitoring API: https://www.arangodb.com/docs/stable/http/monitoring.html

Please let me know if you still have questions.

**Comment by nikita-vanyasin** [comment]
@neha-kapila94 we will prepare a better documentation for alert rules examples. Will keep you updated 👌🏻

**Comment by neha-kapila94** [comment]
@nikita-vanyasin I can't find the alert rules in above resources
