### ISSUE TITLE
'--startCoordinator false --startDBserver false ' it does not work

### ISSUE THREAD

**Issue by dxb350352** [arangodb-helper/arangodb#43]
I have runed 5 instance:
Machine A: ./arangodb --dataDir /home/arango/data/ --agencySize 5 
Machine B:./arangodb --join 192.168.130.201 --dataDir /home/arango/data/
Machine C:./arangodb --join 192.168.130.201 --dataDir /home/arango/data/
Machine C:./arangodb --startDBserver false --startCoordinator false --join 192.168.130.201 --dataDir /home/arango/data1/
Machine C:./arangodb --startDBserver false --startCoordinator false --join 192.168.130.201 --dataDir /home/arango/data2/

I saw 5 coordinators and DBserver are serving

**Comment by ewoutp** [comment]
It appears there is a difference between `--startCoordinator false` and `--startCoordinator=false`.
The first does not work properly, the last one does.

**Comment by ewoutp** [comment]
`github.com/spf32/pflag` is considering `--someArg false` the same as `--someArg=true false` where `false` is an additional argument.

The starter is being modified to fail in case of these (unwanted) additional arguments.

That will be in the next release (eta soon). 
To solve your problem, use `--startCoordinator=false`.

**Comment by dxb350352** [comment]
thank you very mush!

**Comment by ewoutp** [comment]
Warning for unexpected arguments is released in 0.7.0.
