### ISSUE TITLE
How to define the path of agent8531, coordinator8529, dbserver8530, setup.json files when clustering?

### ISSUE THREAD

**Issue by quki** [arangodb-helper/arangodb#63]
I found that 4 files/directories(agent8531, coordinator8529, dbserver8530, setup.json) are created on current path when execute clustering commands(e.g arangodb --server.join A).

How to define the path of those files/directories explicitly?

**Comment by ewoutp** [comment]
You can set the folder in which this directories/setup file are created using `--starter.data-dir=basefolder`

The names of the sub-folders & setup.json is fixed.
