### ISSUE TITLE
Question about ArangoDB cluster

### ISSUE THREAD

**Issue by quki** [arangodb-helper/arangodb#80]
In order to cluster host A(master), B, C on each different machine.

To cluster 3 machine in daemon, I executed 3 commands below 

On host A
`nohup arangodb --starter.data-dir=/mypath/arangodb/ &`

On host B
`nohup arangodb --starter.join A(ip adress for A) --starter.data-dir=/mypath/arangodb/ &`

On host C
`nohup arangodb --starter.join A(ip adress for A) --starter.data-dir=/mypath/arangodb/ &`

And I got 3 coordinators(port:8529), 3 db servers(port:8530) and 3 agents(port:8531) then clustered successfully.

And I use java client for basic CRUD to cluster.
`ArangoDB arangoDB = new ArangoDB.Builder().host(hostA, PORT).build();`
hostA: host of A(master), PORT: 8529

I have a question about this!

If host A(master) dead, any request to host A is blocked and connection refused.

Is there any way to redirecting to another alive node(in this situation B,C) in cluster automatically when host A is dead?

**Comment by ewoutp** [comment]
I'm not aware of all details of the java driver, but I understand that you can configure it to use multiple hosts by giving all addresses and separating them with a `a`.

Took that from this example:
```
  arangodb.hosts=127.0.0.1:8529,127.0.0.1:8529
  arangodb.user=root
  arangodb.password=
```

see https://github.com/arangodb/arangodb-java-driver
