### ISSUE TITLE
Can I start arangodb cluster as authentication true?

### ISSUE THREAD

**Issue by quki** [arangodb-helper/arangodb#83]
I did below command when starting arangodb cluster.
`arangodb --starter.data-dir=/home1/irteam/apps/arangodb/`
but in this case **arangod.conf** file has 'authentication = false' in coordinator8529, dbserver8530, agent8531

Is there any option or way to start arangodb cluster as authentication true mode?

[server]
authentication = false
endpoint = tcp://[::]:8529
threads = 16
[log]
level = INFO
[javascript]
v8-contexts = 4

**Comment by dashdeep13** [comment]
Use the argument
arangodb --auth.jwt-secret=./jwtSecret
where jwtSecret is a file which can have contents like:
 echo "MakeThisSecretMuchStronger" > jwtSecret
