### ISSUE TITLE
Agency size 1 and local mode

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/arangodb#89]
If one combines the options `--cluster.agency-size 1` and `--starter.local` one gets a cluster with one coordinator, one dbserver and one agent. I would have expected to get a cluster with 3 coordinators, 3 dbservers and one agent. If I want the former, I can simply use `--cluster.agency-size 1` alone.

**Comment by ewoutp** [comment]
what is the usecase for this?

**Comment by ewoutp** [comment]
Fixed in 0.10.0
