### ISSUE TITLE
Local `arangodb` does not seem to be able to use docker image

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/arangodb#90]
I have installed `arangodb` locally and then tried to use `--docker.image neunhoef/arangodb:3.3.candidate` to make it use a docker image for the ArangoDB cluster. This did not work, it does not use the docker image but rather tries to launch a local executable. Is this intended or could this be fixed?

**Comment by ewoutp** [comment]
This is by design. We decided a long time ago that in order to run docker, the starter has to run in docker also
