### ISSUE TITLE
Can I start a arangodb based on a configuration file?  

### ISSUE THREAD

**Issue by zhenruyan** [arangodb-helper/arangodb#97]
Based on the configuration file start, more convenient operation dimension

**Comment by ewoutp** [comment]
Right now this is not an option.
Of course you can create a small script will all options already added.
We'll consider if we want to add this.

**Comment by zhenruyan** [comment]
All right
What should I do if I like to turn on password verification?

server.authentication=true     

There's no way to take it.

**Comment by ewoutp** [comment]
Configure a jwt secret. That enables authentication.
See https://github.com/arangodb-helper/arangodb/#authentication-options
