### ISSUE TITLE
Allow for homebrew/other packing system build

### ISSUE THREAD

**Issue by ewoutp** [arangodb-helper/arangodb#98]
Requirements:
- Sources in directory A
- All build artifacts & temp files in directory B
- Sources directory does not need a `.git` folder
- No docker requirement
- Include info from VERSION file (excluded the git build)

Should:
- Fail if go version is too old

**Comment by ewoutp** [comment]
@dothebart Please comment

**Comment by dothebart** [comment]
Yes, we should continue like that to work on https://github.com/arangodb/arangodb/issues/3604
